import React from 'react';
import { DocsCodeBlock } from '../components/DocsCodeBlock';
import { ArrowUpRight, Sparkles, ShieldAlert } from 'lucide-react';

export interface DocSection {
  id: string;
  title: string;
  category: string;
  content: React.ReactNode;
}

export const docsSections: DocSection[] = [
  {
    id: 'overview',
    title: 'Overview',
    category: 'Introduction',
    content: (
      <div className="space-y-6">
        <div>
          <h2 className="text-2xl font-serif font-medium text-zinc-100 tracking-tight">
            Forge by Modula Project
          </h2>
          <p className="mt-2 text-sm text-zinc-400 leading-relaxed font-sans">
            Forge is a quiet creative journal and thinking companion. It exists
            to solve a fundamental creative dilemma:
            <span className="text-zinc-200 font-medium">
              {' '}
              some thoughts deserve to exist before they make sense
            </span>
            . In traditional note-taking and knowledge-base systems, users are
            pressured to categorize, tag, and structure raw ideas immediately.
            Forge inverts this by separating capture from synthesis.
          </p>
        </div>

        <div className="p-4 rounded-xl border border-zinc-800/80 bg-zinc-900/40 space-y-2">
          <div className="flex items-center gap-2 text-pink-400 text-xs font-mono font-medium">
            <Sparkles className="w-4 h-4" />
            <span>The Core Thinking Loop</span>
          </div>
          <p className="text-xs text-zinc-300 font-mono">
            Capture &rarr; Think &rarr; Grow
          </p>
          <p className="text-xs text-zinc-400 font-sans leading-relaxed">
            1. <strong>Capture:</strong> Deposit a half-formed intuition into a
            Fragment seed without friction.
            <br />
            2. <strong>Think:</strong> Unfold observations over time. Request
            gentle reflection from Owl AI when curious.
            <br />
            3. <strong>Grow:</strong> Pin resonant thoughts as Sparks and
            witness synthesis emerge organically.
          </p>
        </div>

        <div>
          <h3 className="text-lg font-serif font-medium text-zinc-200">
            Domain Mental Model
          </h3>
          <ul className="mt-3 space-y-2 text-xs text-zinc-300 font-sans leading-relaxed">
            <li>
              <strong className="text-zinc-100">Fragment:</strong> The
              foundational container for a line of inquiry, started with a seed
              thought.
            </li>
            <li>
              <strong className="text-zinc-100">Seed Thought:</strong> The
              primordial text that initiated the fragment.
            </li>
            <li>
              <strong className="text-zinc-100">Thought Entry:</strong>{' '}
              Chronological reflections and journal entries appended by the
              thinker.
            </li>
            <li>
              <strong className="text-zinc-100">Owl Observation:</strong>{' '}
              Subtle, non-prescriptive AI perspectives generated by Gemini
              (`gemini-2.5-flash`).
            </li>
            <li>
              <strong className="text-zinc-100">Spark:</strong> A pinned thought
              or observation marked by the thinker as significant.
            </li>
            <li>
              <strong className="text-zinc-100">Growth:</strong> A reflective
              synthesis capturing the maturity stage and milestones of the
              fragment.
            </li>
          </ul>
        </div>

        <div className="border-l-2 border-pink-500/80 pl-4 py-1 text-xs text-zinc-400 italic">
          &ldquo;Owl observes. The thinker decides.&rdquo; Forge never pretends
          to think for you.
        </div>
      </div>
    ),
  },
  {
    id: 'philosophy',
    title: 'Philosophy',
    category: 'Introduction',
    content: (
      <div className="space-y-6">
        <h2 className="text-2xl font-serif font-medium text-zinc-100 tracking-tight">
          Product Philosophy
        </h2>
        <p className="text-sm text-zinc-400 leading-relaxed font-sans">
          Forge is intentionally built around three foundational pillars of
          thoughtful software:
        </p>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="p-4 rounded-xl border border-zinc-800/80 bg-zinc-900/40">
            <span className="text-[11px] font-mono text-pink-400">
              Pillar 01
            </span>
            <h4 className="text-sm font-medium text-zinc-200 mt-1 font-serif">
              A thought doesn’t need to be complete to be worth capturing.
            </h4>
            <p className="text-xs text-zinc-400 mt-2 leading-relaxed">
              Premature structuring kills raw creativity. In Forge, fragments
              can exist as half-sentences, questions, or intuitions without
              guilt.
            </p>
          </div>

          <div className="p-4 rounded-xl border border-zinc-800/80 bg-zinc-900/40">
            <span className="text-[11px] font-mono text-pink-400">
              Pillar 02
            </span>
            <h4 className="text-sm font-medium text-zinc-200 mt-1 font-serif">
              Capture first. Understand later.
            </h4>
            <p className="text-xs text-zinc-400 mt-2 leading-relaxed">
              Frictionless capture allows you to deposit ideas into the soil
              before your inner critic demands a folder, a tag, or a deadline.
            </p>
          </div>

          <div className="p-4 rounded-xl border border-zinc-800/80 bg-zinc-900/40">
            <span className="text-[11px] font-mono text-pink-400">
              Pillar 03
            </span>
            <h4 className="text-sm font-medium text-zinc-200 mt-1 font-serif">
              Forge doesn’t think for you. It helps you think.
            </h4>
            <p className="text-xs text-zinc-400 mt-2 leading-relaxed">
              AI should never substitute human inquiry. The thinker remains the
              author, interpreter, and final decider of what everything means.
            </p>
          </div>
        </div>
      </div>
    ),
  },
  {
    id: 'architecture',
    title: 'Architecture',
    category: 'Architecture',
    content: (
      <div className="space-y-6">
        <h2 className="text-2xl font-serif font-medium text-zinc-100 tracking-tight">
          System Architecture
        </h2>
        <p className="text-sm text-zinc-400 leading-relaxed font-sans">
          Forge is structured as a clean monorepo separating a modern React +
          TypeScript single page application from an API-driven Ruby on Rails
          backend:
        </p>

        <DocsCodeBlock
          language="text"
          title="Monorepo Structure"
          code={`forge/
├── frontend_react_ts/     # React 19 + TypeScript frontend (Vite, Tailwind v4, TanStack Query)
│   ├── src/
│   │   ├── app/           # App root, providers, routing, queryClient
│   │   ├── components/    # Atomic UI design system (atoms, templates)
│   │   ├── features/      # Feature modules (auth, fragments, growth, landing, docs)
│   │   ├── hooks/         # Shared custom React hooks
│   │   ├── services/      # Typed API client services
│   │   └── types/         # TypeScript contracts & domain models
│   └── vercel.json        # SPA client rewrites for production
│
├── backend_rails/         # Ruby on Rails 8 API & domain logic
│   ├── app/
│   │   ├── controllers/   # Controllers (API v1 namespace & public Docs)
│   │   ├── models/        # User, Fragment, Observation, Profile
│   │   └── services/      # OwlService (Gemini AI integration)
│   ├── config/            # Routes, CORS, database configuration
│   ├── Dockerfile         # Multi-stage production container
│   ├── railway.json       # Railway deployment manifest
│   └── public/            # OpenAPI 3.0 specification & static assets
│
├── AGENTS.md              # Cross-stack engineering rules & standards
└── CHANGELOG.md           # Keep a Changelog revision history`}
        />

        <div className="space-y-3">
          <h3 className="text-base font-serif font-medium text-zinc-200">
            Production Request Pipeline
          </h3>
          <div className="p-4 rounded-xl border border-zinc-800 bg-zinc-950 font-mono text-xs text-zinc-300 space-y-2">
            <div>Browser / Thinker Client</div>
            <div className="text-pink-400 pl-4">
              &darr; HTTPS (Vercel CDN Edge)
            </div>
            <div>React 19 SPA (frontend_react_ts)</div>
            <div className="text-pink-400 pl-4">
              &darr; REST API with Credentials &amp; Cookies
            </div>
            <div>Rails 8.0.5 Backend on Railway (backend_rails)</div>
            <div className="text-pink-400 pl-4">&darr; Internal Network</div>
            <div className="flex gap-8">
              <span>&bull; PostgreSQL (Railway Managed)</span>
              <span>&bull; Google Gemini Flash 2.5 (Owl AI)</span>
            </div>
          </div>
        </div>
      </div>
    ),
  },
  {
    id: 'local-development',
    title: 'Local Development',
    category: 'Development',
    content: (
      <div className="space-y-6">
        <h2 className="text-2xl font-serif font-medium text-zinc-100 tracking-tight">
          Local Development Setup
        </h2>
        <p className="text-sm text-zinc-400 leading-relaxed font-sans">
          This environment setup reflects the verified configuration on Linux /
          Manjaro:
        </p>

        <div className="space-y-4">
          <h3 className="text-base font-serif font-medium text-zinc-200">
            Prerequisites
          </h3>
          <ul className="list-disc list-inside text-xs text-zinc-300 space-y-1.5 font-mono">
            <li>Ruby 4.0.5 (managed via rbenv or chruby)</li>
            <li>Bundler 4.x (ensure PATH includes user gem bin)</li>
            <li>PostgreSQL 16+ (running on socket / localhost:5432)</li>
            <li>Node.js 20+ &amp; npm 10+</li>
          </ul>
        </div>

        <div className="space-y-3">
          <h3 className="text-base font-serif font-medium text-zinc-200">
            1. Backend Setup
          </h3>
          <p className="text-xs text-zinc-400">
            Ensure your database is initialized and run migrations:
          </p>
          <DocsCodeBlock
            language="bash"
            code={`cd backend_rails
bundle install
bin/rails db:prepare
bin/rails server -b 0.0.0.0 -p 3000`}
          />
        </div>

        <div className="space-y-3">
          <h3 className="text-base font-serif font-medium text-zinc-200">
            2. Frontend Setup
          </h3>
          <p className="text-xs text-zinc-400">
            In a separate terminal, install node dependencies and launch the
            Vite dev server:
          </p>
          <DocsCodeBlock
            language="bash"
            code={`cd frontend_react_ts
npm install
npm run dev`}
          />
        </div>

        <div className="p-4 rounded-xl border border-zinc-800/80 bg-zinc-900/40 text-xs text-zinc-300">
          The Vite dev server runs at{' '}
          <code className="text-pink-400 font-mono">http://localhost:5173</code>{' '}
          and automatically proxies{' '}
          <code className="text-pink-400 font-mono">/api</code> requests to
          Rails at{' '}
          <code className="text-pink-400 font-mono">http://127.0.0.1:3000</code>
          .
        </div>
      </div>
    ),
  },
  {
    id: 'frontend-dev',
    title: 'Frontend Development',
    category: 'Development',
    content: (
      <div className="space-y-6">
        <h2 className="text-2xl font-serif font-medium text-zinc-100 tracking-tight">
          Frontend Development
        </h2>
        <p className="text-sm text-zinc-400 leading-relaxed font-sans">
          The client is built with React 19, TypeScript, and Tailwind CSS v4
          using an Atomic Design and feature-oriented architecture.
        </p>

        <div className="space-y-3">
          <h3 className="text-base font-serif font-medium text-zinc-200">
            Core Technologies
          </h3>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 text-xs font-mono">
            <div className="p-2.5 rounded-lg border border-zinc-800 bg-zinc-900/50 text-zinc-300">
              React 19.2
            </div>
            <div className="p-2.5 rounded-lg border border-zinc-800 bg-zinc-900/50 text-zinc-300">
              TypeScript 6.0
            </div>
            <div className="p-2.5 rounded-lg border border-zinc-800 bg-zinc-900/50 text-zinc-300">
              Vite 8.3
            </div>
            <div className="p-2.5 rounded-lg border border-zinc-800 bg-zinc-900/50 text-zinc-300">
              Tailwind CSS v4
            </div>
            <div className="p-2.5 rounded-lg border border-zinc-800 bg-zinc-900/50 text-zinc-300">
              TanStack Query v5
            </div>
            <div className="p-2.5 rounded-lg border border-zinc-800 bg-zinc-900/50 text-zinc-300">
              Motion 13
            </div>
          </div>
        </div>

        <div className="space-y-3">
          <h3 className="text-base font-serif font-medium text-zinc-200">
            Session Hydration &amp; State
          </h3>
          <p className="text-xs text-zinc-400 leading-relaxed">
            Authentication state is managed via{' '}
            <code className="text-pink-400 font-mono">AuthProvider</code> using
            TanStack Query. It exposes three explicit states:{' '}
            <code className="text-pink-400 font-mono">unknown</code>,{' '}
            <code className="text-pink-400 font-mono">authenticated</code>, and{' '}
            <code className="text-pink-400 font-mono">unauthenticated</code>.
            While in <code className="text-pink-400 font-mono">unknown</code>{' '}
            state during initial hydration, navigation CTAs display stable
            skeleton placeholders to completely eliminate UI flicker.
          </p>
        </div>
      </div>
    ),
  },
  {
    id: 'backend-dev',
    title: 'Backend Development',
    category: 'Development',
    content: (
      <div className="space-y-6">
        <h2 className="text-2xl font-serif font-medium text-zinc-100 tracking-tight">
          Backend Development
        </h2>
        <p className="text-sm text-zinc-400 leading-relaxed font-sans">
          The backend is an API-first Ruby on Rails 8 application configured
          with PostgreSQL and Puma.
        </p>

        <div className="space-y-3">
          <h3 className="text-base font-serif font-medium text-zinc-200">
            Key Architectural Patterns
          </h3>
          <ul className="space-y-2 text-xs text-zinc-300 font-sans leading-relaxed">
            <li>
              <strong>Namespaced API:</strong> All modern client endpoints
              reside under{' '}
              <code className="text-pink-400 font-mono">/api/v1/</code>,
              returning strictly shaped JSON responses.
            </li>
            <li>
              <strong>Session Authentication:</strong> Secure encrypted
              HTTP-only session cookies with{' '}
              <code className="text-pink-400 font-mono">
                credentials: &quot;include&quot;
              </code>{' '}
              across origins.
            </li>
            <li>
              <strong>CORS Policy:</strong> Configured in{' '}
              <code className="text-pink-400 font-mono">
                config/initializers/cors.rb
              </code>{' '}
              to support Vite dev origins and Vercel domains.
            </li>
            <li>
              <strong>Owl AI Service:</strong> Encapsulated in{' '}
              <code className="text-pink-400 font-mono">
                app/services/owl_service.rb
              </code>{' '}
              calling Gemini 2.5 Flash via Faraday.
            </li>
          </ul>
        </div>

        <DocsCodeBlock
          language="ruby"
          title="OwlService Reflection Call"
          code={`# app/services/owl_service.rb
class OwlService
  def self.observe(fragment)
    # Gathers context from seed and thoughts
    # Requests reflective questions from Gemini Flash
    # Never provides prescriptive directives
  end
end`}
        />
      </div>
    ),
  },
  {
    id: 'testing',
    title: 'Testing',
    category: 'Verification',
    content: (
      <div className="space-y-6">
        <h2 className="text-2xl font-serif font-medium text-zinc-100 tracking-tight">
          Testing Strategy &amp; CI Gate
        </h2>
        <p className="text-sm text-zinc-400 leading-relaxed font-sans">
          Both frontend and backend maintain targeted test suites to prevent
          regressions without testing trivial boilerplate.
        </p>

        <div className="space-y-3">
          <h3 className="text-base font-serif font-medium text-zinc-200">
            Frontend Testing &amp; Linting
          </h3>
          <DocsCodeBlock
            language="bash"
            code={`cd frontend_react_ts

# Run Vitest unit & schema tests
npm test

# Run Rust-powered oxlint linter
npm run lint

# Verify full production build & TypeScript types
npm run build`}
          />
        </div>

        <div className="space-y-3">
          <h3 className="text-base font-serif font-medium text-zinc-200">
            Backend Rails Testing
          </h3>
          <DocsCodeBlock
            language="bash"
            code={`cd backend_rails

# Run full Rails Minitest suite
bin/rails test`}
          />
        </div>

        <div className="p-4 rounded-xl border border-zinc-800/80 bg-zinc-900/40 text-xs text-zinc-300">
          <strong className="text-zinc-100">
            Before Opening a Pull Request:
          </strong>{' '}
          Ensure all gates pass in order:{' '}
          <code className="text-pink-400 font-mono">
            npm run lint &rarr; npm test &rarr; bin/rails test &rarr; npm run
            build
          </code>
          .
        </div>
      </div>
    ),
  },
  {
    id: 'environment-variables',
    title: 'Environment Variables',
    category: 'Configuration',
    content: (
      <div className="space-y-6">
        <h2 className="text-2xl font-serif font-medium text-zinc-100 tracking-tight">
          Environment Variables
        </h2>
        <p className="text-sm text-zinc-400 leading-relaxed font-sans">
          Configuration is driven by environment variables. Reference template
          files are maintained at{' '}
          <code className="text-pink-400 font-mono">
            backend_rails/.env.example
          </code>{' '}
          and{' '}
          <code className="text-pink-400 font-mono">
            frontend_react_ts/.env.example
          </code>
          .
        </p>

        <div className="p-4 rounded-xl border border-rose-900/50 bg-rose-950/20 text-xs text-rose-300 flex items-start gap-3">
          <ShieldAlert className="w-5 h-5 flex-shrink-0 text-rose-400 mt-0.5" />
          <div>
            <strong className="text-rose-200">Critical Security Rule:</strong>{' '}
            The frontend bundle must NEVER contain Google/Gemini API keys, Rails
            master keys, or private database passwords. All AI synthesis is
            mediated securely by the Rails backend.
          </div>
        </div>

        <div className="space-y-3">
          <h3 className="text-base font-serif font-medium text-zinc-200">
            Backend Variables (
            <code className="text-pink-400 font-mono">backend_rails/.env</code>)
          </h3>
          <div className="overflow-x-auto">
            <table className="w-full text-xs text-left border border-zinc-800 rounded-lg">
              <thead className="bg-zinc-900/80 text-zinc-300 font-mono">
                <tr>
                  <th className="p-2.5 border-b border-zinc-800">Variable</th>
                  <th className="p-2.5 border-b border-zinc-800">Purpose</th>
                  <th className="p-2.5 border-b border-zinc-800">
                    Default / Example
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-800/60 font-mono text-[11px] text-zinc-400">
                <tr>
                  <td className="p-2.5 text-pink-400">RAILS_ENV</td>
                  <td className="p-2.5 font-sans">Rails environment</td>
                  <td className="p-2.5">development / production</td>
                </tr>
                <tr>
                  <td className="p-2.5 text-pink-400">DATABASE_URL</td>
                  <td className="p-2.5 font-sans">
                    PostgreSQL connection string
                  </td>
                  <td className="p-2.5">
                    postgresql://localhost:5432/forge_dev
                  </td>
                </tr>
                <tr>
                  <td className="p-2.5 text-pink-400">RAILS_MASTER_KEY</td>
                  <td className="p-2.5 font-sans">
                    Master key for credentials decryption
                  </td>
                  <td className="p-2.5">From config/master.key</td>
                </tr>
                <tr>
                  <td className="p-2.5 text-pink-400">GOOGLE_API_KEY</td>
                  <td className="p-2.5 font-sans">
                    Gemini Flash API Key for Owl
                  </td>
                  <td className="p-2.5">AIzaSy...</td>
                </tr>
                <tr>
                  <td className="p-2.5 text-pink-400">FRONTEND_ORIGIN</td>
                  <td className="p-2.5 font-sans">
                    Allowed CORS origin with credentials
                  </td>
                  <td className="p-2.5">http://localhost:5173</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <div className="space-y-3">
          <h3 className="text-base font-serif font-medium text-zinc-200">
            Frontend Variables (
            <code className="text-pink-400 font-mono">
              frontend_react_ts/.env
            </code>
            )
          </h3>
          <div className="overflow-x-auto">
            <table className="w-full text-xs text-left border border-zinc-800 rounded-lg">
              <thead className="bg-zinc-900/80 text-zinc-300 font-mono">
                <tr>
                  <th className="p-2.5 border-b border-zinc-800">Variable</th>
                  <th className="p-2.5 border-b border-zinc-800">Purpose</th>
                  <th className="p-2.5 border-b border-zinc-800">
                    Default / Example
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-800/60 font-mono text-[11px] text-zinc-400">
                <tr>
                  <td className="p-2.5 text-pink-400">VITE_API_BASE_URL</td>
                  <td className="p-2.5 font-sans">
                    Backend URL for production API calls
                  </td>
                  <td className="p-2.5">
                    http://127.0.0.1:3000 (empty in dev)
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    ),
  },
  {
    id: 'deployment',
    title: 'Deployment',
    category: 'Deployment',
    content: (
      <div className="space-y-6">
        <h2 className="text-2xl font-serif font-medium text-zinc-100 tracking-tight">
          Deployment Guide (Vercel &amp; Railway)
        </h2>

        <div className="space-y-3">
          <h3 className="text-base font-serif font-medium text-zinc-200">
            1. Frontend on Vercel
          </h3>
          <p className="text-xs text-zinc-400 leading-relaxed font-sans">
            Connect the GitHub repository to Vercel and configure:
          </p>
          <ul className="list-disc list-inside text-xs text-zinc-300 space-y-1 font-mono">
            <li>
              <strong>Root Directory:</strong>{' '}
              <code className="text-pink-400">frontend_react_ts</code>
            </li>
            <li>
              <strong>Framework Preset:</strong> Vite
            </li>
            <li>
              <strong>Build Command:</strong>{' '}
              <code className="text-pink-400">npm run build</code>
            </li>
            <li>
              <strong>Output Directory:</strong>{' '}
              <code className="text-pink-400">dist</code>
            </li>
            <li>
              <strong>Environment Variable:</strong>{' '}
              <code className="text-pink-400">
                VITE_API_BASE_URL=https://your-backend.up.railway.app
              </code>
            </li>
          </ul>
          <p className="text-xs text-zinc-400 mt-2 font-sans">
            The committed{' '}
            <code className="text-pink-400 font-mono">vercel.json</code> rewrite
            rule routes all requests to{' '}
            <code className="text-pink-400 font-mono">index.html</code>,
            preventing 404 errors on direct React Router refreshes.
          </p>
        </div>

        <div className="space-y-3">
          <h3 className="text-base font-serif font-medium text-zinc-200">
            2. Backend on Railway
          </h3>
          <p className="text-xs text-zinc-400 leading-relaxed font-sans">
            Deploy the Rails backend to Railway using the included Dockerfile
            and railway manifest:
          </p>
          <ul className="list-disc list-inside text-xs text-zinc-300 space-y-1 font-mono">
            <li>
              <strong>Root Directory:</strong>{' '}
              <code className="text-pink-400">backend_rails</code>
            </li>
            <li>
              <strong>Configuration:</strong>{' '}
              <code className="text-pink-400">railway.json</code> (builder:
              DOCKERFILE, healthcheck: /up)
            </li>
            <li>
              <strong>Database:</strong> Add a Railway PostgreSQL service and
              attach its <code className="text-pink-400">DATABASE_URL</code>
            </li>
            <li>
              <strong>Automated Migrations:</strong>{' '}
              <code className="text-pink-400">bin/docker-entrypoint</code>{' '}
              executes{' '}
              <code className="text-pink-400">bin/rails db:prepare</code>{' '}
              automatically on boot
            </li>
          </ul>
        </div>

        <div className="space-y-3">
          <h3 className="text-base font-serif font-medium text-zinc-200">
            3. Healthcheck Endpoint
          </h3>
          <p className="text-xs text-zinc-400 font-sans leading-relaxed">
            Railway monitors the backend via{' '}
            <code className="text-pink-400 font-mono">GET /up</code> which
            returns HTTP 200 <code className="text-pink-400 font-mono">OK</code>
            . This verifies server liveness and Puma readiness.
          </p>
        </div>
      </div>
    ),
  },
  {
    id: 'api-reference',
    title: 'API Reference',
    category: 'API & Schemas',
    content: (
      <div className="space-y-6">
        <h2 className="text-2xl font-serif font-medium text-zinc-100 tracking-tight">
          API Reference &amp; OpenAPI Specification
        </h2>
        <p className="text-sm text-zinc-400 leading-relaxed font-sans">
          The Rails backend exposes complete, interactive OpenAPI 3.0
          documentation powered by Swagger UI.
        </p>

        <div className="p-5 rounded-2xl border border-pink-500/30 bg-gradient-to-r from-pink-950/20 to-zinc-900/50 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <h4 className="text-base font-serif font-medium text-zinc-100">
              Interactive Swagger Explorer
            </h4>
            <p className="text-xs text-zinc-400 mt-1">
              Inspect all real routes, request parameters, schemas, and test
              live queries.
            </p>
          </div>
          <div className="flex items-center gap-3">
            <a
              href="/api/docs"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg bg-pink-600 hover:bg-pink-500 text-white text-xs font-medium shadow-md shadow-pink-600/20 transition-colors"
            >
              Open Swagger UI <ArrowUpRight className="w-4 h-4" />
            </a>
            <a
              href="/api/openapi.json"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-zinc-800 hover:bg-zinc-700 text-zinc-300 text-xs font-mono transition-colors"
            >
              Raw JSON
            </a>
          </div>
        </div>

        <div className="space-y-3">
          <h3 className="text-base font-serif font-medium text-zinc-200">
            Endpoint Summary
          </h3>
          <div className="overflow-x-auto font-mono text-xs">
            <table className="w-full text-left border border-zinc-800 rounded-lg">
              <thead className="bg-zinc-900 text-zinc-300">
                <tr>
                  <th className="p-2 border-b border-zinc-800">Method</th>
                  <th className="p-2 border-b border-zinc-800">Route</th>
                  <th className="p-2 border-b border-zinc-800">Description</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-800/60 text-zinc-400 text-[11px]">
                <tr>
                  <td className="p-2 text-blue-400 font-semibold">POST</td>
                  <td className="p-2 text-zinc-200">/api/v1/auth/register</td>
                  <td className="p-2 font-sans">
                    Register new thinker account
                  </td>
                </tr>
                <tr>
                  <td className="p-2 text-blue-400 font-semibold">POST</td>
                  <td className="p-2 text-zinc-200">/api/v1/auth/login</td>
                  <td className="p-2 font-sans">Sign in to existing account</td>
                </tr>
                <tr>
                  <td className="p-2 text-rose-400 font-semibold">DELETE</td>
                  <td className="p-2 text-zinc-200">/api/v1/auth/logout</td>
                  <td className="p-2 font-sans">Clear session cookie</td>
                </tr>
                <tr>
                  <td className="p-2 text-emerald-400 font-semibold">GET</td>
                  <td className="p-2 text-zinc-200">/api/v1/me</td>
                  <td className="p-2 font-sans">
                    Retrieve active user profile
                  </td>
                </tr>
                <tr>
                  <td className="p-2 text-emerald-400 font-semibold">GET</td>
                  <td className="p-2 text-zinc-200">/api/v1/fragments</td>
                  <td className="p-2 font-sans">List user fragments</td>
                </tr>
                <tr>
                  <td className="p-2 text-blue-400 font-semibold">POST</td>
                  <td className="p-2 text-zinc-200">/api/v1/fragments</td>
                  <td className="p-2 font-sans">
                    Capture initial fragment seed
                  </td>
                </tr>
                <tr>
                  <td className="p-2 text-emerald-400 font-semibold">GET</td>
                  <td className="p-2 text-zinc-200">/api/v1/fragments/:id</td>
                  <td className="p-2 font-sans">
                    Retrieve fragment with observations
                  </td>
                </tr>
                <tr>
                  <td className="p-2 text-blue-400 font-semibold">POST</td>
                  <td className="p-2 text-zinc-200">
                    /api/v1/fragments/:id/entries
                  </td>
                  <td className="p-2 font-sans">
                    Append thinker thought entry
                  </td>
                </tr>
                <tr>
                  <td className="p-2 text-blue-400 font-semibold">POST</td>
                  <td className="p-2 text-zinc-200">
                    /api/v1/fragments/:id/owl/observe
                  </td>
                  <td className="p-2 font-sans">Request Owl AI observation</td>
                </tr>
                <tr>
                  <td className="p-2 text-blue-400 font-semibold">POST</td>
                  <td className="p-2 text-zinc-200">
                    /api/v1/observations/:id/spark
                  </td>
                  <td className="p-2 font-sans">
                    Pin thought as resonant spark
                  </td>
                </tr>
                <tr>
                  <td className="p-2 text-emerald-400 font-semibold">GET</td>
                  <td className="p-2 text-zinc-200">
                    /api/v1/fragments/:id/growth
                  </td>
                  <td className="p-2 font-sans">
                    Synthesize growth milestones
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    ),
  },
  {
    id: 'troubleshooting',
    title: 'Troubleshooting',
    category: 'Support',
    content: (
      <div className="space-y-6">
        <h2 className="text-2xl font-serif font-medium text-zinc-100 tracking-tight">
          Troubleshooting &amp; Known Fixes
        </h2>
        <p className="text-sm text-zinc-400 leading-relaxed font-sans">
          Proven solutions to common setup issues encountered during the build:
        </p>

        <div className="space-y-4">
          <div className="p-4 rounded-xl border border-zinc-800 bg-zinc-900/40 space-y-2">
            <h4 className="text-sm font-medium text-zinc-200 font-mono">
              1. Bundler executable warning on Manjaro
            </h4>
            <p className="text-xs text-zinc-400 leading-relaxed font-sans">
              Warning:{' '}
              <em>
                &quot;You don&apos;t have ~/.local/share/gem/ruby/3.4.0/bin in
                your PATH&quot;
              </em>
              .
            </p>
            <p className="text-xs text-zinc-300 font-sans">
              <strong>Solution:</strong> Add the user gem bin directory to your
              shell profile (
              <code className="text-pink-400 font-mono">~/.zshrc</code> or{' '}
              <code className="text-pink-400 font-mono">~/.bashrc</code>):
            </p>
            <DocsCodeBlock
              language="bash"
              code={`export PATH="$HOME/.local/share/gem/ruby/3.4.0/bin:$PATH"`}
            />
          </div>

          <div className="p-4 rounded-xl border border-zinc-800 bg-zinc-900/40 space-y-2">
            <h4 className="text-sm font-medium text-zinc-200 font-mono">
              2. PostgreSQL cluster uninitialized
            </h4>
            <p className="text-xs text-zinc-400 leading-relaxed font-sans">
              Error:{' '}
              <em>&quot;/var/lib/postgres/data is missing or empty&quot;</em>.
            </p>
            <p className="text-xs text-zinc-300 font-sans">
              <strong>Solution:</strong> Initialize the cluster as user{' '}
              <code className="text-pink-400 font-mono">postgres</code> and
              start the service:
            </p>
            <DocsCodeBlock
              language="bash"
              code={`sudo -u postgres initdb --locale=C.UTF-8 --encoding=UTF8 -D '/var/lib/postgres/data'
sudo systemctl start postgresql
sudo -u postgres createuser -s $(whoami)`}
            />
          </div>

          <div className="p-4 rounded-xl border border-zinc-800 bg-zinc-900/40 space-y-2">
            <h4 className="text-sm font-medium text-zinc-200 font-mono">
              3. Vercel SPA Direct Link Refresh 404
            </h4>
            <p className="text-xs text-zinc-400 leading-relaxed font-sans">
              Reloading routes like{' '}
              <code className="text-pink-400 font-mono">/docs</code> or{' '}
              <code className="text-pink-400 font-mono">/app</code> returns 404
              on Vercel.
            </p>
            <p className="text-xs text-zinc-300 font-sans">
              <strong>Solution:</strong> Verify that{' '}
              <code className="text-pink-400 font-mono">
                frontend_react_ts/vercel.json
              </code>{' '}
              exists with rewrites to{' '}
              <code className="text-pink-400 font-mono">/index.html</code>.
            </p>
          </div>
        </div>
      </div>
    ),
  },
];
